try:
    function1()
    print("Function 1 called.")
    function2()
    print("Function 2 called.")
except:
    print("An exception was raised.")
print("Continuing program.") 